#!/bin/bash

source "scripts/utils/enviroment.sh"


if [ ! -f "$PATH_CONFIG" ]; then

    "$DIR_SCRIPTS/config.sh"

    exit 2

fi


require_source "config"



if [ "$APP_RUN_WITH_TEST" = "1" ]; then 

    "$DIR_SCRIPTS/test.sh" --show 'Automatic testing' --message 'All is well!' --run-test; 

    if [ "$1" = "test" ]; then exit 0; fi

fi


if [ -z $1 ] || [ `ls ./$DIR_SCRIPTS | grep $1.sh -c` = 0 ]
then SCRIPT="show.sh"
else SCRIPT="$1.sh"
fi

if [ -z $2 ] || [ `ls -dl */ | grep "\s$2/$" -c` = 0 ]
then SCRIPT_PARAM=$DIR_DIARY
else SCRIPT_PARAM=$2
fi

"$DIR_SCRIPTS/$SCRIPT" $SCRIPT_PARAM $3 $4 $5
