#!/bin/bash

source "scripts/utils/enviroment.sh"


if [ ! -f "$PATH_CONFIG" ]; then

    "$DIR_SCRIPTS/config.sh"

    exit 2

fi


require_source "config"



if [ "$APP_RUN_WITH_TEST" = "1" ]; then 

    "$DIR_SCRIPTS/test.sh"

    if [ "$1" = "test" ]; then exit 0; fi

fi


if [ -z $1 ] || [ `ls ./$DIR_SCRIPTS | grep $1.sh -c` = 0 ]
then SCRIPT="show.sh"
else SCRIPT="$1.sh"
fi

if [ -z $2 ] || [ `ls -dl */ | grep "\s$2/$" -c` = 0 ]
then SCRIPT_PARAM=$DIR_DIARY
else SCRIPT_PARAM=$2
fi


# Secure multi-word parameters
# Fixed issue #8 (https://github.com/v3b6a7t/git-diary/issues/8#issuecomment-662005174)

for (( i=((${#BASH_ARGV[@]}-2)); i>=0; i-- )); do

    if [[ "${BASH_ARGV[$i]}" =~ " " ]]
    then SECURE_PARAMS="$SECURE_PARAMS \"${BASH_ARGV[$i]}\""
    else SECURE_PARAMS="$SECURE_PARAMS ${BASH_ARGV[$i]}"
    fi

done


"$DIR_SCRIPTS/$SCRIPT" $SCRIPT_PARAM $SECURE_PARAMS
