#!/bin/bash

DIR=`dirname $0`

source "scripts/utils/enviroment"


function test_result() {

    if [ ! -z "$2" ]
    then echo -e "\e[92m OK '$1': $2 \e[0m"
    else echo -e "\e[91m ER '$1': NOT_EXISTS \e[0m"
    fi

}


function do_require_test() {

    # $1 -- Name of the required file
    # $2 -- The name of the variable derived from the file
    
    TESTED="$2"
    require_source "$1"
    test_result $1 ${!TESTED}

}


function do_existence_test() {

    # $1 -- Name of the file

    DIRNAME=`dirname "$1"`

    if [ ! -d "$DIRNAME" ]
    then test_result "$DIRNAME" ""   # Dirname don't exists
    fi

    if [ `ls -l $1* 2>/dev/null | wc -l` -gt 0 ]
    then test_result "$1" "EXISTS"    # File exists
    else test_result "$1" ""          # File don't exists
    fi

}
