#!/bin/bash

# FIXING ISSUES #8 
# https://github.com/v3b6a7t/git-diary/issues/8#issuecomment-662005174


source "scripts/utils/enviroment"

require_source "display"


unset $__SHOW
unset $__MODE

get_run_param "--show"
get_run_param "--mode"

if [ -z "$__SHOW" ] && [ -z "$__MODE" ]; then

    display_info "STEP 1: Enter the command:";
    display_warning "$0 --show \"Ala ma kota - Burka\" --mode \"Ola  ma  Asa\""; echo

    exit 1

else

    display_info "STEP 2: Captured parameters"; echo

    echo "SHOW --> $__SHOW"
    echo "MODE --> $__MODE"

fi


display_info "STEP 3: Passed parameters"; echo

echo "PARAMS-1: ${#@}"    
echo "PARAMS-1: ${@}"
echo "PARAMS-2: ${*}"
echo
echo "PARAMS-3: ${#BASH_ARGV[@]}"
echo "PARAMS-3: ${BASH_ARGV[@]}"
echo "PARAMS-3: ${BASH_ARGV[*]}"
echo 



for (( i=((${#BASH_ARGV[@]})); i>=0; i-- )); do

    if [[ "${BASH_ARGV[$i]}" =~ " " ]]
    then SECURE_PARAMS="$SECURE_PARAMS \"${BASH_ARGV[$i]// /_}\""
    else SECURE_PARAMS="$SECURE_PARAMS ${BASH_ARGV[$i]}"
    fi

done


get_run_param "--end"

if [ -z "$__END" ]; then

    display_info "STEP 4: Process parameters and use them again"; echo

    "./$0" $SECURE_PARAMS --end yes

fi
