#!/bin/bash

DIR=`dirname $0`

source "$DIR/utils/enviroment"


# REQUIRE SOURCES

require_source "config"
require_source "display"


# DETERMINATION VALUES OF VARIABLES

if [ -z "$1" ]; then
    display_warning "Required parameter!"; echo
    exit 1
fi



# ==================================
# SCRIPT FUNCTIONS DEFINITIONS
# ==================================


function info_message() {

    display info begin
    echo " Cleaning has been done! "
    echo " You can now use the command: "
    echo " './run config' or './run install' " 
    display info end

}


function clean_data_config() {

    if [ -d "$DIR_CONFIG" ]; then rm -r "$DIR_CONFIG"; fi
    if [ ! -d "$DIR_CONFIG" ]; then info_message; fi
}


function clean_data_diary() {
    if [ -d "$DIR_DIARY" ]; then 
        rm -r "$DIR_DIARY"; 
    fi
}


function clean_data_ssh() {
    "$DIR/ssh" "--delete"
}


function clean_data() {    
    
    case "$1" in
    
        "data")     clean_data_diary
                    ;;

        "ssh")      clean_data_ssh
                    ;; 

        "hard")     clean_data_ssh
                    clean_data_config
                    ;;

        *)          display warning begin
                    echo "I do not know what to do!"
                    echo "Choose the following option:"
                    echo "--data    To delete the '$DIR_DIARY' directory"
                    echo "--ssh     To delete the ssh keys"
                    echo "--hard    To delete ssh keys and configuration"
                    display warning end
                    ;;

    esac

}


# ==================================
# BODY SCRIPT
# ==================================


case "$1" in

    "$DIR_DIARY" )
            CLEAN_MODE=`echo $@ | grep -oP "\-{2}\w+"`
            clean_data ${CLEAN_MODE:2}
            ;;
    
    *)      display_warning "This clean option for '$1' is not supported!"; echo
            ;;

esac
